services:
  web:
    container_name: test-web-app
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    networks:
      - some-net

  prometheus:
    container_name: prometheus-server
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - prometheus:/etc/prometheus
    networks:
      - some-net
volumes:
  prometheus:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus
networks:
  some-net:
    driver: bridge

